const PDFDocument = require("pdfkit");

const downloadReport = (req, res) => {

    const {
        fullName,
        username,
        email,
        score,
        risk
    } = req.body;

    const doc = new PDFDocument({
        margin: 50
    });

    res.setHeader(
        "Content-Type",
        "application/pdf"
    );

    res.setHeader(
        "Content-Disposition",
        "attachment; filename=DigiTrace_Report.pdf"
    );

    doc.pipe(res);

    // ================= HEADER =================

    doc
        .fillColor("#0EA5E9")
        .fontSize(28)
        .text("DIGITRACE", {
            align: "center"
        });

    doc
        .fillColor("black")
        .fontSize(16)
        .text(
            "Digital Footprint & Privacy Risk Assessment Report",
            {
                align: "center"
            }
        );

    doc.moveDown();

    doc.moveTo(50, 110)
       .lineTo(550, 110)
       .stroke();

    // ================= REPORT INFO =================

    const reportId = "DT-" + Date.now();

    const today = new Date().toLocaleString();

    doc.moveDown();

    doc.fontSize(12);

    doc.text(`Report ID : ${reportId}`);
    doc.text(`Generated : ${today}`);

    doc.moveDown();

    // ================= USER DETAILS =================

    doc
        .fillColor("#0EA5E9")
        .fontSize(16)
        .text("USER DETAILS");

    doc.fillColor("black");

    doc.fontSize(12);

    doc.text(`Full Name : ${fullName}`);
    doc.text(`Username  : ${username}`);
    doc.text(`Email     : ${email}`);

    doc.moveDown();

    // ================= PRIVACY =================

    doc
        .fillColor("#0EA5E9")
        .fontSize(16)
        .text("PRIVACY ASSESSMENT");

    doc.fillColor("black");

    doc.fontSize(12);

    doc.text(`Privacy Score : ${score}%`);
    doc.text(`Risk Level    : ${risk}`);

    doc.moveDown();

    // ================= SUMMARY =================

    doc
        .fillColor("#0EA5E9")
        .fontSize(16)
        .text("ANALYSIS SUMMARY");

    doc.fillColor("black");

    doc.fontSize(12);

    doc.list([
        "Username Analysis Completed",
        "Email Exposure Checked",
        "Reverse Image Metadata Analyzed",
        "Privacy Report Generated Successfully"
    ]);

    doc.moveDown();

    // ================= RECOMMENDATIONS =================

    doc
        .fillColor("#0EA5E9")
        .fontSize(16)
        .text("RECOMMENDATIONS");

    doc.fillColor("black");

    doc.fontSize(12);

    doc.list([
        "Use a strong and unique password.",
        "Enable Two-Factor Authentication (2FA).",
        "Avoid sharing personal information publicly.",
        "Review social media privacy settings regularly.",
        "Use different passwords for different accounts.",
        "Monitor online accounts for suspicious activity."
    ]);

    doc.moveDown(2);

    doc.moveTo(50, 720)
       .lineTo(550, 720)
       .stroke();

    doc.moveDown();

    doc
        .fillColor("gray")
        .fontSize(10)
        .text(
            "Generated by DigiTrace - Digital Footprint & Privacy Risk Assessment Tool",
            {
                align: "center"
            }
        );

    doc.end();

};

module.exports = {
    downloadReport
};